# 
# Configuration file for BannerText Minecraft Plugin
# https://www.spigotmc.org/resources/bannertext.49049/
#
chat:
  tag: "&8[&3BannerText&8]&r "
  help-page: |
    &6%s
    &b%s
    &7&a%s
    %s
  cmd-format: "&d%s &f- &7%s"
  messages:
    NO_PERMS: "&cYou do not have permission to do that!"
    NOT_PLAYER: "&cYou must be a player to do that!"
    BAD_CMD: "&cUnknown command given: %s"
    BAD_USAGE: "&cBad usage: &6%s"
    BAD_ARG: "&cBad argument: &e%s"
    ERR_WRITER: "&cCould not get a writer: &6%s"
    ERR_BANNERS: "&cCould not get banners: &6%s"
    GOT_WRITER: "&aGot a writer successfully!"
    GOT_BANNERS: "&aGot banners successfully!"
    DID_CONFIG: "&6The config was reloaded by &e%s"
  commands:
    ROOT:
      usage: "/bannertext"
      description: "displays plugin help & info"
    GET:
      usage: "/bannertext get <text...>"
      description: "converts the given text into banners"
    WRITE:
      usage: "/bannertext write <text...>"
      description: "creates a banner writer tool for the given text"
    RELOAD:
      usage: "/bannertext reloadconfig"
      description: "reloads the plugin's configuration file"

# setting this true will require new banners
# to be made for lower case characters.
case-sensitive: false

# Below are listed all of the characters that can be converted into banners.
# If you decide to add more patterns, here's an example of the format:
# 
# {CHARACTER}:                  # A single character that can be read from the game chat
#   {STYLE}:                    # Can be default, obfuscated, bold, strike, underline, or italic.
#     - Banner: {FRONT?}        # All banners should start with a base 'Banner' pattern.
#     - {MORE SHAPES}: {FRONT?} # Add as many patterns as you need to the banner.
# 
# {FRONT?} tells the plugin what color each pattern will be.
# It will be either 'yes' for text color or 'no' for background.
# 
# Here are two different lists for valid pattern names:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/banner/PatternType.html
#
# Banner                   # Saltire                     # Per Fess
# Base Dexter Canton       # Cross                       # Per Pale Inverted
# Base Sinister Canton     # Cross                       # Per Fess Inverted
# Chief Dexter Canton      # Chevron                     # Bordure
# Chief Sinister Canton    # Inverted Chevron            # Bordure Indented
# Base                     # Base Indented               # Creeper Charge
# Chief                    # Chief Indented              # Gradient
# Pale Dexter              # Per Bend Sinister           # Base Gradient
# Pale Sinister            # Per Bend                    # Field Masoned
# Pale                     # Per Bend Inverted           # Skull Charge
# Fess                     # Per Bend Sinister Inverted  # Flower Charge
# Bend                     # Roundel                     # Mojang Charge
# Bend Sinister            # Lozenge
# Paly                     # Per Pale
#
# Examples of each shape: https://minecraft.gamepedia.com/Banner_Pattern#Usage
# Online banner-making tool: http://www.planetminecraft.com/banner/
#
# Borderless letters from: https://www.youtube.com/watch?v=jLYvPD_vbZg
# Bordered letters from: https://www.youtube.com/watch?v=PncIlxt8TtI
# Numbers & symbols from: https://www.youtube.com/watch?v=xODU7WWTXYE
#
banners:
  A:
    default:
      - Banner: yes
      - Per Fess: no
      - Base: no
      - Pale Sinister: yes
      - Pale Dexter: yes
      - Chief: yes
      - Bordure: no
    bold:
      - Banner: no
      - Chief: yes
      - Pale Dexter: yes
      - Pale Sinister: yes
      - Fess: yes
  B:
    default:
      - Banner: yes
      - Pale: no
      - Base: yes
      - Chief: yes
      - Fess: yes
      - Bordure: no
    bold:
      - Banner: no
      - Chief: yes
      - Pale Dexter: yes
      - Pale Sinister: yes
      - Fess: yes
      - Base: yes
  C:
    default:
      - Banner: no
      - Pale Dexter: yes
      - Chief: yes
      - Base: yes
      - Bordure: no
    bold:
      - Banner: no
      - Chief: yes
      - Base: yes
  D:
    default:
      - Banner: no
      - Pale Dexter: yes
      - Base: yes
      - Per Bend: no
      - Bend: yes
      - Bordure: no
    bold:
      - Banner: yes
      - Lozenge: no
      - Chief: yes
      - Base: yes
      - Pale Dexter: yes
  E:
    default:
      - Banner: no
      - Fess: yes
      - Pale Sinister: no
      - Pale Dexter: yes
      - Chief: yes
      - Base: yes
      - Bordure: no
    bold:
      - Banner: no
      - Fess: yes
      - Pale Sinister: no
      - Base: yes
      - Chief: yes
      - Pale Dexter: yes
  F:
    default:
      - Banner: no
      - Fess: yes
      - Pale Sinister: no
      - Pale Dexter: yes
      - Chief: yes
      - Bordure: no
    bold:
      - Banner: no
      - Fess: yes
      - Pale Sinister: no
      - Pale Dexter: yes
      - Chief: yes
  G:
    default:
      - Banner: no
      - Pale Sinister: yes
      - Per Fess: no
      - Base: yes
      - Pale Dexter: yes
      - Chief: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale Sinister: yes
      - Per Fess: no
      - Base: yes
      - Pale Dexter: yes
      - Chief: yes
  H:
    default:
      - Banner: no
      - Fess: yes
      - Pale Sinister: yes
      - Pale Dexter: yes
      - Bordure: no
    bold:
      - Banner: yes
      - Chief: no
      - Base: no
      - Pale Dexter: yes
      - Pale Sinister: yes
  I:
    default:
      - Banner: no
      - Chief: yes
      - Base: yes
      - Pale: yes
      - Bordure: no
    bold:
      - Banner: no
      - Base: yes
      - Chief: yes
      - Pale: yes
  J:
    default:
      - Banner: no
      - Pale Dexter: yes
      - Per Fess: no
      - Base: yes
      - Pale Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale Dexter: yes
      - Per Fess: no
      - Base: yes
      - Pale Sinister: yes
  K:
    default:
      - Banner: no
      - Pale Dexter: yes
      - Pale Dexter: yes
      - Fess: yes
      - Per Pale Inverted: no
      - Saltire: yes
      - Bordure: no
    bold:
      - Banner: no
      - Fess: yes
      - Pale Sinister: no
      - Bend Sinister: yes
      - Bend: yes
      - Pale Dexter: yes
  L:
    default:
      - Banner: no
      - Pale Dexter: yes
      - Base: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale Dexter: yes
      - Base: yes
  M:
    default:
      - Banner: no
      - Inverted Chevron: yes
      - Chief Indented: no
      - Pale Dexter: yes
      - Pale Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Inverted Chevron: yes
      - Chief Indented: no
      - Pale Dexter: yes
      - Pale Sinister: yes
  N:
    default:
      - Banner: no
      - Pale Dexter: yes
      - Per Bend: no
      - Bend: yes
      - Pale Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale Dexter: yes
      - Inverted Chevron: no
      - Pale Sinister: yes
      - Bend: yes
  O:
    default:
      - Banner: no
      - Pale Dexter: yes
      - Chief: yes
      - Pale Sinister: yes
      - Base: yes
      - Bordure: no
    bold:
      - Banner: no
      - Chief: yes
      - Pale Sinister: yes
      - Base: yes
      - Pale Dexter: yes
  P:
    default:
      - Banner: yes
      - Per Fess: no
      - Pale Sinister: yes
      - Base: no
      - Pale Dexter: yes
      - Chief: yes
      - Bordure: no
    bold:
      - Banner: yes
      - Per Fess: no
      - Pale Sinister: yes
      - Base: no
      - Chief: yes
      - Pale Dexter: yes
  Q:
    default:
      - Banner: no
      - Pale Dexter: yes
      - Chief: yes
      - Pale Sinister: yes
      - Base: yes
      - Bordure: no
      - Base Sinister Canton: yes
    bold:
      - Banner: no
      - Bend: yes
      - Per Fess: no
      - Pale Dexter: yes
      - Base: yes
      - Pale Sinister: yes
      - Chief: yes
  R:
    default:
      - Banner: no
      - Saltire: yes
      - Per Pale: no
      - Per Fess: yes
      - Fess: yes
      - Pale Dexter: yes
      - Bordure: no
    bold:
      - Banner: yes
      - Per Fess Inverted: no
      - Bend: yes
      - Per Pale: no
      - Pale Dexter: yes
      - Chief: yes
      - Fess: yes
  S:
    default:
      - Banner: no
      - Base: yes
      - Chief: yes
      - Bend: yes
      - Bordure: no
    bold:
      - Banner: no
      - Inverted Chevron: yes
      - Chevron: yes
      - Chief Sinister Canton: yes
      - Base Dexter Canton: yes
      - Lozenge: no
      - Bend: yes
  T:
    default:
      - Banner: no
      - Chief: yes
      - Pale: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale: yes
      - Chief: yes
  U:
    default:
      - Banner: no
      - Pale Dexter: yes
      - Base: yes
      - Pale Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Base: yes
      - Pale Sinister: yes
      - Pale Dexter: yes
  V:
    default:
      - Banner: no
      - Pale Dexter: yes
      - Chevron: no
      - Bend Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale Dexter: yes
      - Chevron: no
      - Bend Sinister: yes
  W:
    default:
      - Banner: no
      - Chevron: yes
      - Base Indented: no
      - Pale Dexter: yes
      - Pale Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Chevron: yes
      - Base Indented: no
      - Pale Sinister: yes
      - Pale Dexter: yes
  X:
    default:
      - Banner: no
      - Chief: yes
      - Base: yes
      - Pale: no
      - Saltire: yes
      - Bordure: no
    bold:
      - Banner: no
      - Bend Sinister: yes
      - Bend: yes
  Y:
    default:
      - Banner: no
      - Saltire: yes
      - Per Pale Inverted: no
      - Bend Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Bend: yes
      - Per Fess Inverted: no
      - Bend Sinister: yes
  Z:
    default:
      - Banner: no
      - Chief: yes
      - Base: yes
      - Bend Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Inverted Chevron: yes
      - Chevron: yes
      - Chief Dexter Canton: yes
      - Base Sinister Canton: yes
      - Lozenge: no
      - Bend Sinister: yes
  0:
    default:
      - Banner: no
      - Chief: yes
      - Pale Sinister: yes
      - Base: yes
      - Pale Dexter: yes
      - Bend Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Chief: yes
      - Pale Sinister: yes
      - Base: yes
      - Pale Dexter: yes
      - Bend Sinister: yes
  1:
    default:
      - Banner: no
      - Chief Dexter Canton: yes
      - Pale: yes
      - Base: yes
      - Bordure: no
    bold:
      - Banner: no
      - Chief Dexter Canton: yes
      - Bordure: no
      - Pale: yes
  2:
    default:
      - Banner: no
      - Chief: yes
      - Lozenge: no
      - Bend Sinister: yes
      - Base: yes
      - Bordure: no
    bold:
      - Banner: no
      - Inverted Chevron: yes
      - Chevron: yes
      - Chief Dexter Canton: yes
      - Base Sinister Canton: yes
      - Lozenge: no
      - Bend Sinister: yes
  3:
    default:
      - Banner: no
      - Fess: yes
      - Pale Dexter: no
      - Base: yes
      - Pale Sinister: yes
      - Chief: yes
      - Bordure: no
    bold:
      - Banner: no
      - Fess: yes
      - Pale Dexter: no
      - Base: yes
      - Pale Sinister: yes
      - Chief: yes
  4:
    default:
      - Banner: yes
      - Per Fess: no
      - Pale Dexter: yes
      - Base: no
      - Pale Sinister: yes
      - Fess: yes
      - Bordure: no
    bold:
      - Banner: yes
      - Per Fess: no
      - Pale Dexter: yes
      - Base: no
      - Pale Sinister: yes
      - Fess: yes
  5:
    default:
      - Banner: no
      - Base: yes
      - Bend: yes
      - Bordure Indented: no
      - Base Dexter Canton: yes
      - Chief: yes
      - Bordure: no
    bold:
      - Banner: yes
      - Per Pale Inverted: no
      - Per Fess Inverted: no
      - Base: yes
      - Per Bend: no
      - Bend: yes
      - Chief: yes
  6:
    default:
      - Banner: yes
      - Per Fess Inverted: no
      - Pale Sinister: yes
      - Chief: no
      - Base: yes
      - Pale Dexter: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale Sinister: yes
      - Per Fess: no
      - Base: yes
      - Fess: yes
      - Pale Dexter: yes
      - Chief: yes
  7:
    default:
      - Banner: no
      - Chief: yes
      - Per Bend Sinister Inverted: no
      - Bend Sinister: yes
      - Base Dexter Canton: yes
      - Bordure: no
    bold:
      - Banner: no
      - Chief: yes
      - Per Bend Sinister Inverted: no
      - Bend Sinister: yes
  8:
    default:
      - Banner: yes
      - Pale: no
      - Base: yes
      - Chief: yes
      - Fess: yes
      - Bordure: no
    bold:
      - Banner: no
      - Chief: yes
      - Pale Dexter: yes
      - Pale Sinister: yes
      - Fess: yes
      - Base: yes
  9:
    default:
      - Banner: yes
      - Per Fess: no
      - Pale Dexter: yes
      - Base: no
      - Chief: yes
      - Pale Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale Dexter: yes
      - Per Fess Inverted: no
      - Fess: yes
      - Chief: yes
      - Pale Sinister: yes
  ' ':
    default:
      - Banner: no
    bold:
      - Banner: no
  '.':
    default:
      - Banner: no
      - Base Dexter Canton: yes
      - Bordure: no
    bold:
      - Banner: no
      - Base Dexter Canton: yes
  ',':
    default:
      - Banner: no
      - Base Dexter Canton: yes
      - Bordure Indented: no
      - Bordure: no
    bold:
      - Banner: no
      - Base Dexter Canton: yes
      - Bordure Indented: no
  '''':
    default:
      - Banner: no
      - Chief Sinister Canton: yes
      - Per Bend Sinister Inverted: no
      - Bordure: no
    bold:
      - Banner: no
      - Chief Sinister Canton: yes
      - Per Bend Sinister Inverted: no
  '"':
    default:
      - Banner: no
      - Chief Sinister Canton: yes
      - Chief Dexter Canton: yes
      - Pale: no
      - Bordure: no
    bold:
      - Banner: no
      - Chief Sinister Canton: yes
      - Chief Dexter Canton: yes
      - Pale: no
  ':':
    default:
      - Banner: no
      - Base Dexter Canton: yes
      - Chief Dexter Canton: yes
      - Bordure: no
    bold:
      - Banner: no
      - Base Dexter Canton: yes
      - Chief Dexter Canton: yes
  ';':
    default:
      - Banner: no
      - Base Dexter Canton: yes
      - Bordure Indented: no
      - Chief Dexter Canton: yes
      - Bordure: no
    bold:
      - Banner: no
      - Base Dexter Canton: yes
      - Bordure Indented: no
      - Chief Dexter Canton: yes
  '!':
    default:
      - Banner: no
      - Per Fess: yes
      - Fess: yes
      - Base Dexter Canton: yes
      - Per Pale Inverted: no
      - Bordure: no
    bold:
      - Banner: no
      - Per Fess: yes
      - Fess: yes
      - Base Dexter Canton: yes
      - Per Pale Inverted: no
  '?':
    default:
      - Banner: no
      - Pale Sinister: yes
      - Per Fess Inverted: no
      - Chief: yes
      - Fess: yes
      - Base Dexter Canton: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale Sinister: yes
      - Per Fess Inverted: no
      - Chief: yes
      - Fess: yes
      - Base Dexter Canton: yes
  '%':
    default:
      - Banner: no
      - Bend Sinister: yes
      - Base Sinister Canton: yes
      - Chief Dexter Canton: yes
      - Bordure: no
    bold:
      - Banner: no
      - Bend Sinister: yes
      - Base Sinister Canton: yes
      - Chief Dexter Canton: yes
  '^':
    default:
      - Banner base: no
      - Chief: yes
      - Lozenge: no
      - Bordure Indented: no
  '*':
    default:
      - Banner: no
      - Flower Charge: yes
      - Lozenge: yes
      - Bordure: no
    bold:
      - Banner: no
      - Flower Charge: yes
      - Lozenge: yes
  '+':
    default:
      - Banner: no
      - Pale: yes
      - Chief: no
      - Base: no
      - Fess: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale: yes
      - Chief: no
      - Base: no
      - Fess: yes
  '-':
    default:
      - Banner: no
      - Fess: yes
      - Bordure: no
    bold:
      - Banner: no
      - Fess: yes
  '=':
    default:
      - Banner: yes
      - Chief: no
      - Fess: no
      - Base: no
      - Bordure: no
    bold:
      - Banner: yes
      - Chief: no
      - Fess: no
      - Base: no
  '/':
    default:
      - Banner: no
      - Bend Sinister: yes
      - Bordure: no
    bold:
      - Banner: no
      - Bend Sinister: yes
  '\':
    default:
      - Banner: no
      - Bend: yes
      - Bordure: no
    bold:
      - Banner: no
      - Bend: yes
  '|':
    default:
      - Banner: no
      - Pale: yes
      - Bordure: no
    bold:
      - Banner: no
      - Pale: yes
  '[':
    default:
      - Banner: no
      - Chief: yes
      - Base: yes
      - Pale Dexter: yes
      - Pale Sinister: no
      - Bordure: no
    bold:
      - Banner: no
      - Chief: yes
      - Base: yes
      - Pale Dexter: yes
      - Pale Sinister: no
  ']':
    default:
      - Banner: no
      - Chief: yes
      - Base: yes
      - Pale Sinister: yes
      - Pale Dexter: no
      - Bordure: no
    bold:
      - Banner: no
      - Chief: yes
      - Base: yes
      - Pale Sinister: yes
      - Pale Dexter: no
  '(':
    default:
      - Banner: no
      - Bend: yes
      - Bend Sinister: yes
      - Per Pale: no
      - Bordure: no
    bold:
      - Banner: no
      - Bend: yes
      - Bend Sinister: yes
      - Per Pale: no
  ')':
    default:
      - Banner: no
      - Bend: yes
      - Bend Sinister: yes
      - Per Pale Inverted: no
      - Bordure: no
    bold:
      - Banner: no
      - Bend: yes
      - Bend Sinister: yes
      - Per Pale Inverted: no
  '{':
    default:
      - Banner: no
      - Bordure Indented: yes
      - Pale: yes
      - Per Pale Inverted: no
      - Base Indented: yes
      - Chief Indented: yes
      - Chief Dexter Canton: yes
      - Base Dexter Canton: yes
      - Bordure: no
    bold:
      - Banner: no
      - Bordure Indented: yes
      - Pale: yes
      - Per Pale Inverted: no
      - Base Indented: yes
      - Chief Indented: yes
  '}':
    default:
      - Banner: no
      - Bordure Indented: yes
      - Pale: yes
      - Per Pale: no
      - Base Indented: yes
      - Chief Indented: yes
      - Chief Sinister Canton: yes
      - Base Sinister Canton: yes
      - Bordure: no
    bold:
      - Banner: no
      - Bordure Indented: yes
      - Pale: yes
      - Per Pale: no
      - Base Indented: yes
      - Chief Indented: yes
