# 
# Configuration file for BannerText Minecraft Plugin
# https://www.spigotmc.org/resources/bannertext.49049/
#
chat:
  tag: "&8[&3BannerText&8]&r "
  help-page: |
    &6--===-( &e%s &6}-===--
    &b%s
    &7&a%s
    %s
  cmd-format: "&d%s &f- &7%s"
  messages:
    NO_PERMS: "&cYou do not have permission to do that!"
    NOT_PLAYER: "&cYou must be a player to do that!"
    BAD_CMD: "&cUnknown command given: %s"
    BAD_USAGE: "&cBad usage: &6%s"
    BAD_ARG: "&cBad argument: &e%s"
    ERR_WRITER: "&cCould not get a writer: &6%s"
    ERR_BANNERS: "&cCould not get banners: &6%s"
    GOT_WRITER: "&aGot a writer successfully!"
    GOT_BANNERS: "&aGot banners successfully!"
    DID_CONFIG: "&6The config was reloaded by &e%s"
  commands:
    ROOT:
      usage: "/bannertext"
      description: "displays plugin help & info"
    GET:
      usage: "/bannertext get <text...>"
      description: "converts the given text into banners"
    WRITE:
      usage: "/bannertext write <text...>"
      description: "creates a banner writer tool for the given text"
    RELOAD:
      usage: "/bannertext reloadconfig"
      description: "reloads the plugin's configuration file"

# setting this true will require new banners
# to be made for lower case characters.
case-sensitive: false

# Below are listed all of the characters that can be converted into banners.
# If you decide to add more patterns, here's an example of the format:
# 
# {CHARACTER}:                  # A single character that can be read from the game chat
#   {STYLE}:                    # Can be default, obfuscated, bold, strike, underline, or italic.
#     - Banner: {FRONT?}        # All banners should start with a base 'Banner' pattern.
#     - {MORE SHAPES}: {FRONT?} # Add as many patterns as you need to the banner.
# 
# {FRONT?} tells the plugin what color each pattern will be.
# It will be either 'true' for text color or 'false' for background.
# 
# Here are two different lists for valid pattern names:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/banner/PatternType.html
#
# Banner                   # Saltire                     # Per Fess
# Base Dexter Canton       # Cross                       # Per Pale Inverted
# Base Sinister Canton     # Cross                       # Per Fess Inverted
# Chief Dexter Canton      # Chevron                     # Bordure
# Chief Sinister Canton    # Inverted Chevron            # Bordure Indented
# Base                     # Base Indented               # Creeper Charge
# Chief                    # Chief Indented              # Gradient
# Pale Dexter              # Per Bend Sinister           # Base Gradient
# Pale Sinister            # Per Bend                    # Field Masoned
# Pale                     # Per Bend Inverted           # Skull Charge
# Fess                     # Per Bend Sinister Inverted  # Flower Charge
# Bend                     # Roundel                     # Mojang Charge
# Bend Sinister            # Lozenge
# Paly                     # Per Pale
#
# Examples of each shape: https://minecraft.gamepedia.com/Banner_Pattern#Usage
# Online banner-making tool: http://www.planetminecraft.com/banner/
#
# Borderless letters from: https://www.youtube.com/watch?v=jLYvPD_vbZg
# Bordered letters from: https://www.youtube.com/watch?v=PncIlxt8TtI
# Numbers & symbols from: https://www.youtube.com/watch?v=xODU7WWTXYE
#
banners:
  A:
    default:
      - Banner: true
      - Per Fess: false
      - Base: false
      - Pale Sinister: true
      - Pale Dexter: true
      - Chief: true
      - Bordure: false
    bold:
      - Banner: false
      - Chief: true
      - Pale Dexter: true
      - Pale Sinister: true
      - Fess: true
  B:
    default:
      - Banner: true
      - Pale: false
      - Base: true
      - Chief: true
      - Fess: true
      - Bordure: false
    bold:
      - Banner: false
      - Chief: true
      - Pale Dexter: true
      - Pale Sinister: true
      - Fess: true
      - Base: true
  C:
    default:
      - Banner: false
      - Pale Dexter: true
      - Chief: true
      - Base: true
      - Bordure: false
    bold:
      - Banner: false
      - Chief: true
      - Base: true
  D:
    default:
      - Banner: false
      - Pale Dexter: true
      - Base: true
      - Per Bend: false
      - Bend: true
      - Bordure: false
    bold:
      - Banner: true
      - Lozenge: false
      - Chief: true
      - Base: true
      - Pale Dexter: true
  E:
    default:
      - Banner: false
      - Fess: true
      - Pale Sinister: false
      - Pale Dexter: true
      - Chief: true
      - Base: true
      - Bordure: false
    bold:
      - Banner: false
      - Fess: true
      - Pale Sinister: false
      - Base: true
      - Chief: true
      - Pale Dexter: true
  F:
    default:
      - Banner: false
      - Fess: true
      - Pale Sinister: false
      - Pale Dexter: true
      - Chief: true
      - Bordure: false
    bold:
      - Banner: false
      - Fess: true
      - Pale Sinister: false
      - Pale Dexter: true
      - Chief: true
  G:
    default:
      - Banner: false
      - Pale Sinister: true
      - Per Fess: false
      - Base: true
      - Pale Dexter: true
      - Chief: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale Sinister: true
      - Per Fess: false
      - Base: true
      - Pale Dexter: true
      - Chief: true
  H:
    default:
      - Banner: false
      - Fess: true
      - Pale Sinister: true
      - Pale Dexter: true
      - Bordure: false
    bold:
      - Banner: true
      - Chief: false
      - Base: false
      - Pale Dexter: true
      - Pale Sinister: true
  I:
    default:
      - Banner: false
      - Chief: true
      - Base: true
      - Pale: true
      - Bordure: false
    bold:
      - Banner: false
      - Base: true
      - Chief: true
      - Pale: true
  J:
    default:
      - Banner: false
      - Pale Dexter: true
      - Per Fess: false
      - Base: true
      - Pale Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale Dexter: true
      - Per Fess: false
      - Base: true
      - Pale Sinister: true
  K:
    default:
      - Banner: false
      - Pale Dexter: true
      - Pale Dexter: true
      - Fess: true
      - Per Pale Inverted: false
      - Saltire: true
      - Bordure: false
    bold:
      - Banner: false
      - Fess: true
      - Pale Sinister: false
      - Bend Sinister: true
      - Bend: true
      - Pale Dexter: true
  L:
    default:
      - Banner: false
      - Pale Dexter: true
      - Base: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale Dexter: true
      - Base: true
  M:
    default:
      - Banner: false
      - Inverted Chevron: true
      - Chief Indented: false
      - Pale Dexter: true
      - Pale Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Inverted Chevron: true
      - Chief Indented: false
      - Pale Dexter: true
      - Pale Sinister: true
  N:
    default:
      - Banner: false
      - Pale Dexter: true
      - Per Bend: false
      - Bend: true
      - Pale Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale Dexter: true
      - Inverted Chevron: false
      - Pale Sinister: true
      - Bend: true
  O:
    default:
      - Banner: false
      - Pale Dexter: true
      - Chief: true
      - Pale Sinister: true
      - Base: true
      - Bordure: false
    bold:
      - Banner: false
      - Chief: true
      - Pale Sinister: true
      - Base: true
      - Pale Dexter: true
  P:
    default:
      - Banner: true
      - Per Fess: false
      - Pale Sinister: true
      - Base: false
      - Pale Dexter: true
      - Chief: true
      - Bordure: false
    bold:
      - Banner: true
      - Per Fess: false
      - Pale Sinister: true
      - Base: false
      - Chief: true
      - Pale Dexter: true
  Q:
    default:
      - Banner: false
      - Pale Dexter: true
      - Chief: true
      - Pale Sinister: true
      - Base: true
      - Bordure: false
      - Base Sinister Canton: true
    bold:
      - Banner: false
      - Bend: true
      - Per Fess: false
      - Pale Dexter: true
      - Base: true
      - Pale Sinister: true
      - Chief: true
  R:
    default:
      - Banner: false
      - Saltire: true
      - Per Pale: false
      - Per Fess: true
      - Fess: true
      - Pale Dexter: true
      - Bordure: false
    bold:
      - Banner: true
      - Per Fess Inverted: false
      - Bend: true
      - Per Pale: false
      - Pale Dexter: true
      - Chief: true
      - Fess: true
  S:
    default:
      - Banner: false
      - Base: true
      - Chief: true
      - Bend: true
      - Bordure: false
    bold:
      - Banner: false
      - Inverted Chevron: true
      - Chevron: true
      - Chief Sinister Canton: true
      - Base Dexter Canton: true
      - Lozenge: false
      - Bend: true
  T:
    default:
      - Banner: false
      - Chief: true
      - Pale: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale: true
      - Chief: true
  U:
    default:
      - Banner: false
      - Pale Dexter: true
      - Base: true
      - Pale Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Base: true
      - Pale Sinister: true
      - Pale Dexter: true
  V:
    default:
      - Banner: false
      - Pale Dexter: true
      - Chevron: false
      - Bend Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale Dexter: true
      - Chevron: false
      - Bend Sinister: true
  W:
    default:
      - Banner: false
      - Chevron: true
      - Base Indented: false
      - Pale Dexter: true
      - Pale Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Chevron: true
      - Base Indented: false
      - Pale Sinister: true
      - Pale Dexter: true
  X:
    default:
      - Banner: false
      - Chief: true
      - Base: true
      - Pale: false
      - Saltire: true
      - Bordure: false
    bold:
      - Banner: false
      - Bend Sinister: true
      - Bend: true
  Y:
    default:
      - Banner: false
      - Saltire: true
      - Per Pale Inverted: false
      - Bend Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Bend: true
      - Per Fess Inverted: false
      - Bend Sinister: true
  Z:
    default:
      - Banner: false
      - Chief: true
      - Base: true
      - Bend Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Inverted Chevron: true
      - Chevron: true
      - Chief Dexter Canton: true
      - Base Sinister Canton: true
      - Lozenge: false
      - Bend Sinister: true
  0:
    default:
      - Banner: false
      - Chief: true
      - Pale Sinister: true
      - Base: true
      - Pale Dexter: true
      - Bend Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Chief: true
      - Pale Sinister: true
      - Base: true
      - Pale Dexter: true
      - Bend Sinister: true
  1:
    default:
      - Banner: false
      - Chief Dexter Canton: true
      - Pale: true
      - Base: true
      - Bordure: false
    bold:
      - Banner: false
      - Chief Dexter Canton: true
      - Bordure: false
      - Pale: true
  2:
    default:
      - Banner: false
      - Chief: true
      - Lozenge: false
      - Bend Sinister: true
      - Base: true
      - Bordure: false
    bold:
      - Banner: false
      - Inverted Chevron: true
      - Chevron: true
      - Chief Dexter Canton: true
      - Base Sinister Canton: true
      - Lozenge: false
      - Bend Sinister: true
  3:
    default:
      - Banner: false
      - Fess: true
      - Pale Dexter: false
      - Base: true
      - Pale Sinister: true
      - Chief: true
      - Bordure: false
    bold:
      - Banner: false
      - Fess: true
      - Pale Dexter: false
      - Base: true
      - Pale Sinister: true
      - Chief: true
  4:
    default:
      - Banner: true
      - Per Fess: false
      - Pale Dexter: true
      - Base: false
      - Pale Sinister: true
      - Fess: true
      - Bordure: false
    bold:
      - Banner: true
      - Per Fess: false
      - Pale Dexter: true
      - Base: false
      - Pale Sinister: true
      - Fess: true
  5:
    default:
      - Banner: false
      - Base: true
      - Bend: true
      - Bordure Indented: false
      - Base Dexter Canton: true
      - Chief: true
      - Bordure: false
    bold:
      - Banner: true
      - Per Pale Inverted: false
      - Per Fess Inverted: false
      - Base: true
      - Per Bend: false
      - Bend: true
      - Chief: true
  6:
    default:
      - Banner: true
      - Per Fess Inverted: false
      - Pale Sinister: true
      - Chief: false
      - Base: true
      - Pale Dexter: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale Sinister: true
      - Per Fess: false
      - Base: true
      - Fess: true
      - Pale Dexter: true
      - Chief: true
  7:
    default:
      - Banner: false
      - Chief: true
      - Per Bend Sinister Inverted: false
      - Bend Sinister: true
      - Base Dexter Canton: true
      - Bordure: false
    bold:
      - Banner: false
      - Chief: true
      - Per Bend Sinister Inverted: false
      - Bend Sinister: true
  8:
    default:
      - Banner: true
      - Pale: false
      - Base: true
      - Chief: true
      - Fess: true
      - Bordure: false
    bold:
      - Banner: false
      - Chief: true
      - Pale Dexter: true
      - Pale Sinister: true
      - Fess: true
      - Base: true
  9:
    default:
      - Banner: true
      - Per Fess: false
      - Pale Dexter: true
      - Base: false
      - Chief: true
      - Pale Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale Dexter: true
      - Per Fess Inverted: false
      - Fess: true
      - Chief: true
      - Pale Sinister: true
  ' ':
    default:
      - Banner: false
    bold:
      - Banner: false
  '.':
    default:
      - Banner: false
      - Base Dexter Canton: true
      - Bordure: false
    bold:
      - Banner: false
      - Base Dexter Canton: true
  ',':
    default:
      - Banner: false
      - Base Dexter Canton: true
      - Bordure Indented: false
      - Bordure: false
    bold:
      - Banner: false
      - Base Dexter Canton: true
      - Bordure Indented: false
  "'":
    default:
      - Banner: false
      - Chief Sinister Canton: true
      - Per Bend Sinister Inverted: false
      - Bordure: false
    bold:
      - Banner: false
      - Chief Sinister Canton: true
      - Per Bend Sinister Inverted: false
  '"':
    default:
      - Banner: false
      - Chief Sinister Canton: true
      - Chief Dexter Canton: true
      - Pale: false
      - Bordure: false
    bold:
      - Banner: false
      - Chief Sinister Canton: true
      - Chief Dexter Canton: true
      - Pale: false
  ':':
    default:
      - Banner: false
      - Base Dexter Canton: true
      - Chief Dexter Canton: true
      - Bordure: false
    bold:
      - Banner: false
      - Base Dexter Canton: true
      - Chief Dexter Canton: true
  ';':
    default:
      - Banner: false
      - Base Dexter Canton: true
      - Bordure Indented: false
      - Chief Dexter Canton: true
      - Bordure: false
    bold:
      - Banner: false
      - Base Dexter Canton: true
      - Bordure Indented: false
      - Chief Dexter Canton: true
  '!':
    default:
      - Banner: false
      - Per Fess: true
      - Fess: true
      - Base Dexter Canton: true
      - Per Pale Inverted: false
      - Bordure: false
    bold:
      - Banner: false
      - Per Fess: true
      - Fess: true
      - Base Dexter Canton: true
      - Per Pale Inverted: false
  '?':
    default:
      - Banner: false
      - Pale Sinister: true
      - Per Fess Inverted: false
      - Chief: true
      - Fess: true
      - Base Dexter Canton: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale Sinister: true
      - Per Fess Inverted: false
      - Chief: true
      - Fess: true
      - Base Dexter Canton: true
  '%':
    default:
      - Banner: false
      - Bend Sinister: true
      - Base Sinister Canton: true
      - Chief Dexter Canton: true
      - Bordure: false
    bold:
      - Banner: false
      - Bend Sinister: true
      - Base Sinister Canton: true
      - Chief Dexter Canton: true
  '^':
    default:
      - Banner: false
      - Chief: true
      - Lozenge: false
      - Bordure Indented: false
  '*':
    default:
      - Banner: false
      - Flower Charge: true
      - Lozenge: true
      - Bordure: false
    bold:
      - Banner: false
      - Flower Charge: true
      - Lozenge: true
  '+':
    default:
      - Banner: false
      - Pale: true
      - Chief: false
      - Base: false
      - Fess: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale: true
      - Chief: false
      - Base: false
      - Fess: true
  '-':
    default:
      - Banner: false
      - Fess: true
      - Bordure: false
    bold:
      - Banner: false
      - Fess: true
  '=':
    default:
      - Banner: true
      - Chief: false
      - Fess: false
      - Base: false
      - Bordure: false
    bold:
      - Banner: true
      - Chief: false
      - Fess: false
      - Base: false
  '/':
    default:
      - Banner: false
      - Bend Sinister: true
      - Bordure: false
    bold:
      - Banner: false
      - Bend Sinister: true
  '\':
    default:
      - Banner: false
      - Bend: true
      - Bordure: false
    bold:
      - Banner: false
      - Bend: true
  '|':
    default:
      - Banner: false
      - Pale: true
      - Bordure: false
    bold:
      - Banner: false
      - Pale: true
  '[':
    default:
      - Banner: false
      - Chief: true
      - Base: true
      - Pale Dexter: true
      - Pale Sinister: false
      - Bordure: false
    bold:
      - Banner: false
      - Chief: true
      - Base: true
      - Pale Dexter: true
      - Pale Sinister: false
  ']':
    default:
      - Banner: false
      - Chief: true
      - Base: true
      - Pale Sinister: true
      - Pale Dexter: false
      - Bordure: false
    bold:
      - Banner: false
      - Chief: true
      - Base: true
      - Pale Sinister: true
      - Pale Dexter: false
  '(':
    default:
      - Banner: false
      - Bend: true
      - Bend Sinister: true
      - Per Pale: false
      - Bordure: false
    bold:
      - Banner: false
      - Bend: true
      - Bend Sinister: true
      - Per Pale: false
  ')':
    default:
      - Banner: false
      - Bend: true
      - Bend Sinister: true
      - Per Pale Inverted: false
      - Bordure: false
    bold:
      - Banner: false
      - Bend: true
      - Bend Sinister: true
      - Per Pale Inverted: false
  '{':
    default:
      - Banner: false
      - Bordure Indented: true
      - Pale: true
      - Per Pale Inverted: false
      - Base Indented: true
      - Chief Indented: true
      - Chief Dexter Canton: true
      - Base Dexter Canton: true
      - Bordure: false
    bold:
      - Banner: false
      - Bordure Indented: true
      - Pale: true
      - Per Pale Inverted: false
      - Base Indented: true
      - Chief Indented: true
  '}':
    default:
      - Banner: false
      - Bordure Indented: true
      - Pale: true
      - Per Pale: false
      - Base Indented: true
      - Chief Indented: true
      - Chief Sinister Canton: true
      - Base Sinister Canton: true
      - Bordure: false
    bold:
      - Banner: false
      - Bordure Indented: true
      - Pale: true
      - Per Pale: false
      - Base Indented: true
      - Chief Indented: true
