#
# plugin.yml for BannerText-1.16.4-0 SpigotMC plugin
# https://www.spigotmc.org/resources/bannertext.49049/
#
main: me.cynadyde.bannertext.BannerTextPlugin
name: BannerText
version: "1.16.4-0"
api-version: "1.13"
description: |
  Swiftly convert chat text into banners. Use '&[0-9a-f][0-9a-f]'
  to set the text and background colors. Use '&[klmnor]' to set
  the text style. Use '&&' to form a literal ampersand.
author: Cynadyde (Feb, 2017)
website: https://www.spigotmc.org/resources/bannertext.49049/
commands:
  bannertext:
    description: "root plugin command"
    aliases:
      - bt
permissions:
  bannertext.*:
    description: "grants access to all plugin features"
    default: op
    children:
      bannertext.get: true
      bannertext.write: true
      bannertext.config: true
  bannertext.get:
    description: "grants ability to use the get command"
    default: false
  bannertext.write:
    description: "grants ability to use the write command"
    default: false
  bannertext.config:
    description: "grants ability to reload the config file"
    default: false
